/*
©2022 Pivotree | All rights reserved
*/
// auth
export const TOGGLE_USER_LOGIN = "TOGGLE_USER_LOGIN";
export const TOGGLE_USER_SUCCESS = "TOGGLE_USER_SUCCESS";
export const TOGGLE_USER_FAILED = "TOGGLE_USER_FAILED";
export const RESET_STORE = "RESET_STORE";

//common
export const SAVE_MENU_STATE = "SAVE_MENU_STATE";
export const SET_FIELDS_JSON = "SET_FIELDS_JSON";
export const SET_FIELDS_STATE = "SET_FIELDS_STATE";
export const CACHE_EVENT_DATA = "CACHE_EVENT_DATA";
export const SET_STEPPER_STATE = "SET_STEPPER_STATE";
export const TOGGLE_SNACKBAR = "TOGGLE_SNACKBAR";
export const TOGGLE_SESSION_PROMPT = "TOGGLE_SESSION_PROMPT";
export const SAVE_LOGGED_IN_DATA = "SAVE_LOGGED_IN_DATA";
export const COMMON_ACTION = "COMMON_ACTION";
export const COMMON_ACTION_SUCCESS = "COMMON_ACTION_SUCCESS";
export const COMMON_ACTION_FAILED = "COMMON_ACTION_FAILED";

//organization
export const SET_ORGANIZATIONS = "SET_ORGANIZATIONS";
export const GET_ORGANIZATIONS = "GET_ORGANIZATIONS";
export const ORGANIZATION_ACTION = "ORGANIZATION_ACTION";
export const ORGANIZATION_ACTION_SUCCESS = "ORGANIZATION_ACTION_SUCCESS";
export const ORGANIZATION_ACTION_FAILED = "ORGANIZATION_ACTION_FAILED";
export const ORGANIZATION_MASTER_DATA = "ORGANIZATION_MASTER_DATA";
export const ORGANIZATION_MASTER_DATA_SUCCESS =
  "ORGANIZATION_MASTER_DATA_SUCCESS";
export const ORGANIZATION_MASTER_DATA_FAILED =
  "ORGANIZATION_MASTER_DATA_FAILED";

//node
export const SET_NODES = "SET_NODES";
export const GET_NODES = "GET_NODES";
export const NODE_ACTION = "NODE_ACTION";
export const NODE_ACTION_SUCCESS = "NODE_ACTION_SUCCESS";
export const NODE_ACTION_FAILED = "NODE_ACTION_FAILED";
export const GET_NODE_QUESTIONNAIRE = "GET_NODE_QUESTIONNAIRE";
export const SET_NODE_QUESTIONNAIRE = "SET_NODE_QUESTIONNAIRE";
export const CHANGE_NODE_QUESTIONNAIRE = "CHANGE_NODE_QUESTIONNAIRE";
export const NODE_MASTER_DATA_SUCCESS = "NODE_MASTER_DATA_SUCCESS";
export const DATA_CREATION = "DATA_CREATION";
export const DATA_CREATION_SUCCESS = "DATA_CREATION_SUCCESS";
export const DATA_CREATION_FAILED = "DATA_CREATION_FAILED";
